### ISSUE TITLE
Can you query state and country levels in addition to address/city?

### ISSUE THREAD

**Issue by couch** [datadesk/jquery-geocodify#11]
If I start typing in state/region or country names like "United States," or "Arkansas," can it autocomplete in those scenarios as well?

**Comment by palewire** [comment]
In short, it could. But it doesn't.

Right now I have it only return things are at the "locality" level or greater, but we could make it return broader results. I honestly haven't thought it through that much. What do you think a sensible default would be?

The other limit is that autocomplete doesn't start firing until you enter five characters, another arbitrary default I picked out of the hat (I was thinking of ZIP Codes). An override option seems obvious there too, but thoughts on the sensible default would also be appreciated.

**Comment by couch** [comment]
I imagine it as on opt, something like specificityBias that's an array of strings or ints that match Google's hierarchal structure and then returns any results that match at those levels. The default could be what you have now, including all levels locality and higher.

**Comment by palewire** [comment]
So you'd want to specify every level we accept. The only other way I can think of would be to set a minimum accuracy level and then have the algorithm return everything at that level or greater. What do you think of that alternative?

**Comment by palewire** [comment]
I added an [acceptableAddressTypes](https://github.com/datadesk/jquery-geocodify/commit/0e84dcd392aa8226ada07a80ebb226b31704b24f) list you can pass in at initialization. It should act as a whitelist, so it should return a result if it contains any of the types in the specified list. You can see the complete set [here](http://code.google.com/apis/maps/documentation/geocoding/#Types). The new default is to return everything.

**Comment by couch** [comment]
That's exactly what I was imagining. I forgot how many types Google has, but I think this is a nice feature to have integrated. Nicely done with the quick implementation.
