### ISSUE TITLE
Single-result handling bug?

### ISSUE THREAD

**Issue by allanjamesvestal** [datadesk/jquery-geocodify#37]
When there's only one result in the array of suggestions with approved types ('keep') the script shows the first item in the list of all results ('results'). But if the first thing in the results array was filtered out won't this bad value show up as the only choice?

(To solve this you'd just have to change all references to 'result' in lines 260-264 so that they referred to 'keep' instead.)

I'd submit this myself but want to hear Ben's input first. Am I right here?

**Comment by schwanksta** [comment]
Pretty sure you're right, but I'm not familiar enough with the purpose of 'force' to say either. @palewire ?

**Comment by palewire** [comment]
Hard to see how you're wrong. I've made the patch.
