### ISSUE TITLE
Opera and jQuery 1.9 compatibility 

### ISSUE THREAD

**Issue by caseycesari** [datadesk/jquery-geocodify#42]
The code to navigate the search results list is using `$.browser` to check for Opera, but `$.browser` was [removed](http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed) from jQuery 1.9. I removed it, and changed the binding to always be `"keydown"`. It seems to be working correctly in both Opera 12.14 and Opera 11 (OSX).

I didn't want to submit a pull request for this just yet, in case there is something else I'm missing, but wanted to alert you to `$.browser` being removed.

Thanks.

**Comment by palewire** [comment]
Excellent. Thanks for hacking at this.

**Comment by caseycesari** [comment]
For sure. Working on an app with a simliar design and functionality to the mayoral map you guys just released. Thought I should contribute a bit.

**Comment by palewire** [comment]
Appreciated. One of my big wishes is to standardize the CSS a little bit more so that it doesn't look odd in Internet Explorer. Though making anything not look odd in IE is probably a week's work.

**Comment by caseycesari** [comment]
I'd be in to pulling out the CSS where possible and creating an external file as a first step towards that.

**Comment by palewire** [comment]
That, and then maybe some skeleton or bootstrap ripoff defaults or something that we know will look steady cross-browser.

**Comment by caseycesari** [comment]
Sounds good. I'll take a stab at it.

**Comment by caseycesari** [comment]
Forgot to close and ref from dbbe38b17bb4ca1419238833208535ff4765e9b1
